import 'dotenv/config';
import http from 'http'; import express from 'express'; import next from 'next'; import {Server} from 'socket.io'; import crypto from 'crypto';
const dev=process.env.NODE_ENV!=='production',port=Number(process.env.PORT||3000),nextApp=next({dev}),handle=(nextApp as any).getRequestHandler(),expressApp=express();
type Mode='text'|'voice'|'video'; type Profile={name:string,gender:'Male'|'Female',age:number}; type User={id:string,mode:Mode,profile?:Profile,room?:string,peer?:string,ip:string,connectedAt:number};
const users=new Map<string,User>(); const queues:Record<Mode,string[]>={text:[],voice:[],video:[]}; const rooms=new Map<string,Set<string>>(); const reports:any[]=[]; const banned=new Set<string>();
const clean=(s:string)=>s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim().slice(0,500); function removeQueue(id:string){for(const q of Object.values(queues)){const i=q.indexOf(id);if(i>=0)q.splice(i,1)}} function broadcastPresence(io:Server){io.emit('presence',users.size)}
nextApp.prepare().then(()=>{expressApp.get('/api/health',(_,res)=>res.json({ok:true,users:users.size,rooms:rooms.size}));expressApp.get('/api/admin',(req,res)=>{if(req.headers.authorization!==`Bearer ${process.env.ADMIN_KEY||'change-me-in-production'}`)return res.status(401).json({error:'unauthorized'});res.json({activeUsers:users.size,currentConversations:rooms.size,reports,bannedIps:[...banned]})});const server=http.createServer((req,res)=>{if(req.url?.startsWith('/api/'))return expressApp(req,res);return handle(req,res)});const io=new Server(server,{cors:{origin:true,credentials:false},maxHttpBufferSize:1e6});
io.use((socket,next)=>{const ip=String(socket.handshake.headers['x-forwarded-for']||socket.handshake.address).split(',')[0].trim();if(banned.has(ip))return next(new Error('banned'));(socket as any).ip=ip;next()});
io.on('connection',socket=>{const id='anonymous_'+crypto.randomBytes(3).toString('hex');const ip=(socket as any).ip as string;users.set(socket.id,{id,mode:'text',ip,connectedAt:Date.now()});broadcastPresence(io);
const join=(mode:Mode,profile:Profile)=>{removeQueue(socket.id);const user=users.get(socket.id);if(!user)return;user.mode=mode;user.profile=profile;const q=queues[mode];let peer:string|undefined;while(q.length&&!peer){const candidate=q.shift()!;if(candidate!==socket.id&&users.has(candidate)&&!users.get(candidate)!.room)peer=candidate}if(!peer){q.push(socket.id);socket.emit('match:waiting');return}const roomId='room_'+crypto.randomBytes(8).toString('hex');rooms.set(roomId,new Set([socket.id,peer]));user.room=roomId;user.peer=peer;const peerUser=users.get(peer)!;peerUser.room=roomId;peerUser.peer=socket.id;socket.join(roomId);io.sockets.sockets.get(peer)?.join(roomId);socket.emit('match:found',{roomId,peerId:peer,initiator:socket.id<peer});io.sockets.sockets.get(peer)?.emit('match:found',{roomId,peerId:socket.id,initiator:socket.id<peer});socket.emit('peer:profile',peerUser.profile);io.sockets.sockets.get(peer)?.emit('peer:profile',user.profile)};
socket.on('match:join',({mode='text',profile}: {mode?:Mode,profile?:Profile})=>{if(!profile||!profile.name||!['Male','Female'].includes(profile.gender)||!Number.isInteger(profile.age)||profile.age<18||profile.age>100)return socket.emit('profile:error');join(mode,profile)});
socket.on('match:next',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){io.sockets.sockets.get(u.peer)?.emit('peer:left');const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}}u.room=undefined;u.peer=undefined;if(u.profile)join(u.mode,u.profile)});
socket.on('match:end',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){io.sockets.sockets.get(u.peer)?.emit('peer:left');const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}}if(u.room)rooms.delete(u.room);u.room=undefined;u.peer=undefined});socket.on('match:cancel',()=>removeQueue(socket.id));
const lastMsgAt=new Map<string,number>();socket.on('message:send',({roomId,text})=>{const u=users.get(socket.id);if(!u||u.room!==roomId)return;const now=Date.now();const previous=lastMsgAt.get(socket.id)||0;if(now-previous<600)return;lastMsgAt.set(socket.id,now);const safe=clean(String(text||''));if(!safe)return;socket.to(roomId).emit('message',{id:crypto.randomUUID(),text:safe})});
socket.on('voice:message',({roomId,data})=>{const u=users.get(socket.id);if(!u||u.room!==roomId||!u.peer||!data)return;try{const size=typeof data==='string'?Buffer.byteLength(data,'base64'):data.byteLength||data.length||0;if(size>900000)return;socket.to(roomId).emit('voice:message',{id:crypto.randomUUID(),data})}catch{}});
socket.on('rtc:offer',({roomId,offer})=>{const u=users.get(socket.id);if(!u||u.room!==roomId||!u.peer)return;io.sockets.sockets.get(u.peer)?.emit('rtc:offer',{roomId,offer,from:socket.id})});socket.on('rtc:answer',({roomId,answer})=>{const u=users.get(socket.id);if(!u||u.room!==roomId||!u.peer)return;io.sockets.sockets.get(u.peer)?.emit('rtc:answer',{roomId,answer,from:socket.id})});socket.on('rtc:ice',({roomId,candidate})=>{const u=users.get(socket.id);if(!u||u.room!==roomId||!u.peer)return;io.sockets.sockets.get(u.peer)?.emit('rtc:ice',{roomId,candidate,from:socket.id})});
socket.on('report',({roomId,reason})=>{const u=users.get(socket.id);if(!u)return;reports.push({id:crypto.randomUUID(),reason:String(reason).slice(0,40),reporter:u.id,reported:u.peer||null,at:new Date().toISOString()});if(u.peer){const p=users.get(u.peer);if(p){banned.add(p.ip);io.sockets.sockets.get(u.peer)?.emit('peer:left');io.sockets.sockets.get(u.peer)?.disconnect(true)}}u.room=undefined;u.peer=undefined});
socket.on('disconnect',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}io.sockets.sockets.get(u.peer)?.emit('peer:left')}if(u.room)rooms.delete(u.room);removeQueue(socket.id);users.delete(socket.id);broadcastPresence(io)});
});server.listen(port,()=>console.log(`Talkly running on http://localhost:${port}`));});
