import 'dotenv/config';
import http from 'http'; import express from 'express'; import next from 'next'; import {Server} from 'socket.io'; import crypto from 'crypto';
const dev=process.env.NODE_ENV!=='production',port=Number(process.env.PORT||3000),app=next({dev}),handle=(app as any).getRequestHandler();
type User={id:string,mode:'text'|'voice'|'video',room?:string,peer?:string,ip:string,connectedAt:number};
const users=new Map<string,User>(); const queues:Record<string,string[]>={text:[],voice:[],video:[]}; const rooms=new Map<string,Set<string>>(); const reports:any[]=[]; const banned=new Set<string>();
const clean=(s:string)=>s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim().slice(0,500); function removeQueue(id:string){for(const q of Object.values(queues)){const i=q.indexOf(id);if(i>=0)q.splice(i,1)}} function broadcastPresence(io:Server){io.emit('presence',users.size)}
app.prepare().then(()=>{const server=http.createServer((req,res)=>handle(req,res));const io=new Server(server,{cors:{origin:true,credentials:false},maxHttpBufferSize:1e6});
io.use((socket,next)=>{const ip=String(socket.handshake.headers['x-forwarded-for']||socket.handshake.address).split(',')[0].trim();if(banned.has(ip))return next(new Error('banned'));(socket as any).ip=ip;next()});
io.on('connection',socket=>{const id='anonymous_'+crypto.randomBytes(3).toString('hex');const ip=(socket as any).ip as string;users.set(socket.id,{id,mode:'text',ip,connectedAt:Date.now()});broadcastPresence(io);
const join=(mode:'text'|'voice'|'video')=>{removeQueue(socket.id);users.get(socket.id)!.mode=mode;const q=queues[mode];let peer:string|undefined;while(q.length&&!peer){const candidate=q.shift()!;if(candidate!==socket.id&&users.has(candidate)&&!users.get(candidate)!.room)peer=candidate}if(!peer){q.push(socket.id);socket.emit('match:waiting');return}const roomId='room_'+crypto.randomBytes(8).toString('hex');rooms.set(roomId,new Set([socket.id,peer]));users.get(socket.id)!.room=roomId;users.get(socket.id)!.peer=peer;users.get(peer)!.room=roomId;users.get(peer)!.peer=socket.id;socket.join(roomId);io.sockets.sockets.get(peer)?.join(roomId);socket.emit('match:found',{roomId,peerId:peer});io.sockets.sockets.get(peer)?.emit('match:found',{roomId,peerId:socket.id})};
socket.on('match:join',({mode='text'})=>join(mode));socket.on('match:next',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){io.sockets.sockets.get(u.peer)?.emit('peer:left');const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}}u.room=undefined;u.peer=undefined;join(u.mode)});socket.on('match:end',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){io.sockets.sockets.get(u.peer)?.emit('peer:left');const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}}if(u.room)rooms.delete(u.room);u.room=undefined;u.peer=undefined});socket.on('match:cancel',()=>removeQueue(socket.id));
const lastMsgAt=new Map<string,number>();socket.on('message:send',({roomId,text})=>{const u=users.get(socket.id);if(!u||u.room!==roomId)return;const now=Date.now();const previous=lastMsgAt.get(socket.id)||0;if(now-previous<600)return;lastMsgAt.set(socket.id,now);const safe=clean(String(text||''));if(!safe)return;socket.to(roomId).emit('message',{id:crypto.randomUUID(),text:safe})});
socket.on('rtc:offer',({roomId,offer})=>{const u=users.get(socket.id);if(!u)return;if(u.room===roomId&&u.peer)io.sockets.sockets.get(u.peer)?.emit('rtc:offer',{offer,from:socket.id})});socket.on('rtc:answer',({roomId,answer})=>{const u=users.get(socket.id);if(!u)return;if(u.room===roomId&&u.peer)io.sockets.sockets.get(u.peer)?.emit('rtc:answer',{answer,from:socket.id})});socket.on('rtc:ice',({roomId,candidate})=>{const u=users.get(socket.id);if(!u)return;if(u.room===roomId&&u.peer)io.sockets.sockets.get(u.peer)?.emit('rtc:ice',{candidate,from:socket.id})});
socket.on('report',({roomId,reason})=>{const u=users.get(socket.id);if(!u)return;reports.push({id:crypto.randomUUID(),reason:String(reason).slice(0,40),reporter:u.id,reported:u.peer||null,at:new Date().toISOString()});if(u.peer){const p=users.get(u.peer);if(p){banned.add(p.ip);io.sockets.sockets.get(u.peer)?.emit('peer:left');io.sockets.sockets.get(u.peer)?.disconnect(true)}}u.room=undefined;u.peer=undefined});
socket.on('disconnect',()=>{const u=users.get(socket.id);if(!u)return;if(u.peer){const p=users.get(u.peer);if(p){p.room=undefined;p.peer=undefined}io.sockets.sockets.get(u.peer)?.emit('peer:left')}if(u.room)rooms.delete(u.room);removeQueue(socket.id);users.delete(socket.id);broadcastPresence(io)});
});
app.get('/api/health',(_,res)=>res.json({ok:true,users:users.size,rooms:rooms.size}));app.get('/api/admin',(req,res)=>{if(req.headers.authorization!==`Bearer ${process.env.ADMIN_KEY||'change-me-in-production'}`)return res.status(401).json({error:'unauthorized'});res.json({activeUsers:users.size,currentConversations:rooms.size,reports,bannedIps:[...banned]})});server.listen(port,()=>console.log(`Talkly running on http://localhost:${port}`));});
